#!/bin/sh

# Xresources
[ -f "~/.Xresources" ] && xrdb -merge -I$HOME ~/.Xresources

# carrega dbus i altres
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Usuari
if [ "$INIT_SYS" = "openrc" ]; then
    sudo rc-service connman start &
else
    sudo systemctl start connmann &
fi
setxkbmap es
