#!/bin/sh

# Xresources
[ -f "~/.Xresources" ] && xrdb -merge -I$HOME ~/.Xresources

# carrega dbus i altres
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# autostart
# Set in the file below the cmds to autostart
[ -x "~/.config/xstart" ] && . "~/.config/xstart"

# WM (the following line is necessary to choose the session in ger_ins)
# exec
